### PR TITLE
fix #1753 update server channel group name

### LINKED ISSUE #1753: server channel group name is not appropriate in netty

### PR DESCRIPTION
**Pull request by darionyaphet**
create a new branch and try to publish a simple patch ~

### CODE REVIEW

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
@darionyaphet 
Thanks for your patch:)

Please follow guideline https://github.com/gearpump/gearpump/blob/master/CommitGuideline.md to commit PR next time, then I don't need to rewrite the commit log :)

**Comment by clockfly** [comment]
merged.

**Comment by darionyaphet** [comment]
thank you for your relay :)  I  will follow it next time .

**Pull request closed without merging**
