### PR TITLE
fix #1981, Support OAuth2 Social login

### LINKED ISSUE #1981: Need to support SSO (oauth2)
Gearpump authentication should be expanded to support single-sign on. 
See https://intel-data.atlassian.net/browse/DPNG-5464.

### PR DESCRIPTION
**Pull request by clockfly**
OAuth2 authentication PR for discussion.

**How to test**

1. enable OAuth2 by changing "gearpump.ui-security.oauth2-authenticator-enabled" to true in gear.conf
2. Set proxy before starting UI server, for example:
   ```
    export JAVA_OPTS=-Dhttp.proxyHost=xx.com -Dhttp.proxyPort=8088 -Dhttps.proxyHost=xx.com -Dhttps.proxyPort=8088
   ```
3. Start the UI server by ```bin\services```
4. It will then show the "social login" buttons.
social
5. Currently, only Google account and Cloudfoundry icons are showed. (NOTE: Cloudfoundry  not tested on real server yet)
6. Click the "Google" icon and see what happens.

**How to configure**
Each OAuth2Authenticator has a config like this:
```
"google" {
        "class" = "io.gearpump.services.security.oauth2.impl.GoogleOAuth2Authenticator"

        ## Replace "127.0.0.1:8090" with your actual project site root URL.
        "callback" = "http://127.0.0.1:8090/login/oauth2/google/callback"

        ## !!NOTE!! Replace clientID and clientSecret with your own Application to avoid
        ## potential privacy leakage.
        "clientId" = "xxxxxxxxxxxxxxxxxxx"
        "clientSecret" = "xxxx"

        ## Available values for default user role: guest, user, admin
        "defaultUserRole" = "guest"

        ## ICon for this OAuth2 provider
        icon = "/icons/google.png"
      }
```

**TODO**
1. Add unit test
2. Find a working cloudfoundry UAA server to test whether the UAA OAuth2 authentication works.

### CODE REVIEW

**Comment by clockfly** [comment]
@karol-brejna-i 
 Please find me a test env for UAA.

**Comment by manuzhang** [comment]
I tried it but failed with the following errors.

snip20160316_1

Any hints?

**Comment by clockfly** [comment]
Have you set the proxy?

export JAVA_OPTS=-Dhttp.proxyHost=xx.com -Dhttp.proxyPort=8088 -Dhttps.proxyHost=xx.com -Dhttps.proxyPort=8088

**Comment by manuzhang** [comment]
Yes.

**Comment by manuzhang** [comment]
+1 for the google part

**Comment by karol-brejna-i** [comment]
@clockfly credentials sent via e-mail. Thanks for the great pace!

**Comment by clockfly** [comment]
@karol-brejna-i 
The UAA authenticator works on my env. Can you help to verify it at your env?

**Comment by karol-brejna-i** [comment]
@clockfly, Sure. Let me build your branch (https://github.com/clockfly/gearpump/tree/issue_1981) and use the binaries with TAP's Gearpump broker to spawn testing cluster instance.

**Comment by clockfly** [comment]
@karol-brejna-i  It is very easy to test. No special setup needed. I will brief the steps here:

1. Download the branch https://github.com/clockfly/gearpump/tree/issue_1981, and make the build.
2. Change gear.conf to 
```
oauth2-authenticator-enabled = true
```
3. Open the UI server, http://127.0.0.1:8090
4.Click the icon next to google icon.
5. It will redirect you to http://login.gearpump.gotapaas.eu
6. Login with admin there, it will redirect you back to Gearpump UI.

NOTE: Please set the proxy for service if you are behind firewall.

**Comment by clockfly** [comment]
@karol-brejna-i 
I have updated the rest api document, please check.

**Comment by stanleyxu2005** [comment]
Lgtm +1

**Pull request merged**
