### PR TITLE
fix #1953 remove unused variable masterPath

### PR DESCRIPTION
**Pull request by darionyaphet**
I debugging gearpump source code in idea and found following code maybe don't used .

```
val masterPath = ActorUtil.getSystemAddress(system).toString + s"/user/$MASTER"
```

So I try to remove it :)

### CODE REVIEW

**Comment by clockfly** [comment]
Thanks @darionyaphet 
Probably you can try to squash all commits into single one using "rebase -i", then there is single entry in the log:)

You can check https://github.com/gearpump/gearpump/blob/master/CommitGuideline.md for howto.

**Comment by darionyaphet** [comment]
Hi @clockfly It seems I have merge pull request into one !  (Actually I'm not very sure )

**Comment by manuzhang** [comment]
@darionyaphet Please try rebase your branch against master first instead of master. I would recommend you checkout a new branch based on latest master and cherry-pick the last commit from this branch.

**Comment by darionyaphet** [comment]
@manuzhang Shoule I create a new branch and recommit this pull request ?

(I found [Pull Request merge process for Gearpump](https://github.com/gearpump/gearpump/blob/master/CommitGuideline.md#pull-request-merge-process-for-gearpump) after I have push it .  )

**Comment by darionyaphet** [comment]
The `issue Id` is create when I create a pull request at github ? This pull request's issue Id is `1953`?

**Comment by manuzhang** [comment]
@darionyaphet Hi, some tips.

1. Please don't work directly on your master, which should only be synced with upstream master
2. The following should work for you 
    a. Create a new branch based on upstream master `git checkout -b fix_1953 upstream/master`
    b. cherry pick `git cherry-pick 91a6490`
    c. push to origin `git push origin fix_1953`
    d. create a new PR based on fix_1953

**Comment by manuzhang** [comment]
It's not #1953. please open a new issue like `unused variable masterPath` and that is your issue id.

**Comment by darionyaphet** [comment]
When I want to take a pull request , I should create a issue first , and then I can get the issue-id . Use this issue-id create a new git branch to commit modify . After pull request is done , remove this branch . Is this the workflow to commit ?

**Comment by manuzhang** [comment]
exactly

**Comment by darionyaphet** [comment]
Fantastic :+1:  I will close this PR and redo it in a new process .

**Pull request closed without merging**
