### PR TITLE
initial code layout for jekyll

### PR DESCRIPTION
**Pull request by kkasravi**

### CODE REVIEW

**Comment by clockfly** [comment]
Hi kam

Can you include the bug id in commit log?

**Comment by clockfly** [comment]
and compile fail:
"[error] (gearpump-streaming/test:compile) Compilation failed
[error] Total time: 268 s, completed Nov 17, 2015 7:47:16 AM'


Looks like merge breaks the build.

**Comment by kkasravi** [comment]
This is odd since docs should not of touched this code
```
[error] /home/travis/build/gearpump/gearpump/streaming/src/test/scala/io/gearpump/streaming/dsl/StreamSpec.scala:68: not found: value parallism
[error]       groupBy(_._1, parallism = 2).
[error]                     ^
```

**Comment by kkasravi** [comment]
I'll redo the merge, perhaps I missed something. It may be delayed since I'm in OR tomorrow.

**Comment by kkasravi** [comment]
Resubmitted PR

**Comment by whjiang** [comment]
+1.

**Pull request merged**
