### PR TITLE
Fixes #1521 minor document changes - readability

### LINKED ISSUE #1521: minor document changes - readability

### PR DESCRIPTION
**Pull request by kkasravi**

### CODE REVIEW

**Comment by clockfly** [comment]
+1

**Comment by clockfly** [comment]
my branch https://github.com/clockfly/gearpump contains more recent updates

**Comment by kkasravi** [comment]
ok, let's merge that too. I started on upgrading to use akka-streams 2.0-M1, have you started anything on that?

**Comment by clockfly** [comment]
Go ahead. 

However, I will stick to 1.0 for now under my branch, to simply the problems.

**Comment by kkasravi** [comment]
ok, i will not merge anything related to 2.0-M1 until later in the week

**Comment by clockfly** [comment]
Hi Kam,

Welcome to do that. I am willing to see that change.
I am working on local branch temporary to fix a case.

**Pull request merged**
